### ISSUE TITLE
Add new views

### ISSUE THREAD

**Issue by Luni-4** [bubblesub/bubblesub#18]
It would be useful to implement different views for bubblesub. The following ones would be really appreciated:

- Subs view
- Subs + Video view
- Subs + Audio view
- Full view (Subs + Video + Audio)

**Comment by rr-** [comment]
Mockups, mockups, mockups.

**Comment by Luni-4** [comment]
Below they are listed the views, widgets positions will be changed such that the space won't be wasted.

- Subs View
![subs](https://user-images.githubusercontent.com/12353765/59975955-aec54700-95be-11e9-9999-276cf4bdb75a.png)

- Audio View
![audio](https://user-images.githubusercontent.com/12353765/59975993-fb108700-95be-11e9-9978-a25530626938.png)

- Video View
![video](https://user-images.githubusercontent.com/12353765/59976001-0c599380-95bf-11e9-8755-1cd59cedbb42.png)

- Full View is already implemented


Some clarifications for the Video View: 
- after the video it will be necessary adding a playback bar in order to move between frames
- remove the volume slider on the left
- add the editor splitter under the playback bar

The console splitter could be placed next to the subs one, but I prefer to give more room to subs and enable the console as an external window from the menu
