### ISSUE TITLE
Create a Github Organization

### ISSUE THREAD

**Issue by Luni-4** [bubblesub/bubblesub#53]
It would be useful to group every repository related to `bubblesub` in a single place. This approach would have the following benefits: 

-  Keep track of the main dependencies of this project in a simpler way
-  Add future bindings in one place

The organization could be composed by these repositories:
- bubblesub
- ass_tag_parser
- pympv (??)
- pyffms2
- pyass (??)
- [bubblesub-plugins](https://github.com/Luni-4/bubblesub-plugins)

**Comment by rr-** [comment]
pympv, pyffms2 and pyass have nothing to do with bubblesub

**Comment by Luni-4** [comment]
Yep, I know, but for "main dependencies" I meant the projects created and maintained by you mainly for `bubblesub`.

**Comment by rr-** [comment]
Done. Let's transfer plugins too, though I'm not sure if they're up to date.

**Comment by Luni-4** [comment]
Thanks for creating the organization! :)

Yeah, they had been updated three days ago

**Comment by Luni-4** [comment]
Could you also add the logo contained in the Readme file as organization image, please?

**Comment by rr-** [comment]
Done

**Comment by Luni-4** [comment]
Thank you! :)
