### ISSUE TITLE
No option to use the system color theme

### ISSUE THREAD

**Issue by mia-0** [bubblesub/bubblesub#55]
I set system colors for a reason. Please respect my choices instead of overriding the color scheme.

**Comment by rr-** [comment]
Feel free to code a pull request for this

**Comment by rr-** [comment]
@lachs0r I outlined something sketchy on `system-palette` branch but I don't like how it defaults to light palette for stuff such as spectrogram colors etc. Let me know what you think

**Comment by Luni-4** [comment]
What about this one @lachs0r?

**Comment by rr-** [comment]
Fixed on master
