### ISSUE TITLE
Implement a refresh operation to reload the subtitles from disk

### ISSUE THREAD

**Issue by Luni-4** [bubblesub/bubblesub#68]
Sometimes it's necessary to do some batch edits in other editors of the subs that are currently loaded in `bubblesub`, so it would be useful to reload them from disk.

**Comment by rr-** [comment]
Do you suppose we should add a new undo point after the user reloads the file, or should we reset the undo stack?

**Comment by Luni-4** [comment]
> Do you suppose we should add a new undo point after the user reloads the file, or should we reset the undo stack?

It would be useful to add a new undo point in order to get back the pre-editor version in case of errors. What do you think about this idea?

**Comment by rr-** [comment]
Sounds good :+1:

**Comment by rr-** [comment]
Implemented on master, forgone the undo approach as it was easier to just reload everything

**Comment by Luni-4** [comment]
Thanks for the implementation! Could you add the Ctrl+F5 shortcut and a menu entry, please?

**Comment by rr-** [comment]
Very good point, added both. Thanks for paying attention

**Comment by Luni-4** [comment]
Thanks a lot to you! :)
