### ISSUE TITLE
Cannot play a video and audio

### ISSUE THREAD

**Issue by Luni-4** [bubblesub/bubblesub#80]
Software versions:
- `Python 3.8`
- `mpv` current `master` branch
- `bubblesub` current `master` branch

Practically, after loading a video and the relative audio track, I can't play them. In addition, when I try to move through the frames, I get this error:

```
2020-11-07 18:43:40.922445 [e] Traceback (most recent call last):
2020-11-07 18:43:40.923432 [e]   File "/home/.local/lib/python3.8/site-packages/bubblesub/ui/mpv.py", line 252, in _on_request_seek
2020-11-07 18:43:40.924027 [e]     self.mpv.seek(ms_to_str(pts), "absolute", "exact")
2020-11-07 18:43:40.924464 [e]   File "/home/.local/lib/python3.8/site-packages/mpv.py", line 1054, in seek
2020-11-07 18:43:40.924891 [e]     self.command('seek', amount, reference, precision)
2020-11-07 18:43:40.925320 [e]   File "/home/.local/lib/python3.8/site-packages/mpv.py", line 1041, in command
2020-11-07 18:43:40.925747 [e]     _mpv_command(self.handle, (c_char_p*len(args))(*args))
2020-11-07 18:43:40.926176 [e]   File "/home/.local/lib/python3.8/site-packages/mpv.py", line 133, in raise_for_ec
2020-11-07 18:43:40.926605 [e]     raise ex(ec, *args)
2020-11-07 18:43:40.927035 [e] SystemError: ('Error running mpv command', -12, (<MpvHandle object at 0x7fc170148940>, <mpv.c_char_p_Array_5 object at 0x7fc16005a640>))
```

**Comment by rr-** [comment]
Sorry, works for me

**Comment by rr-** [comment]
Did you reinstall the dependencies?

**Comment by Luni-4** [comment]
Yep, I tried to:
- Completely remove `bubblesub`, even from the `.config` directory
- Reinstall the `python-mpv` dependency

I'm wondering if this issue might be caused by a missing `mpv` building option, but the seek command works from command line.

Need to create some external python-mpv scripts to verify where the problem is

**Comment by Luni-4** [comment]
```
import mpv

player = mpv.MPV(ytdl=False, osc=True, loglevel="info", log_handler=print)
player.seek("00:01:14.0", "absolute", "exact")
player.play('/path/to/file.mkv')
player.wait_for_playback()
```

It doesn't work, so it's a `python-mpv` problem. Reporting upstream

**Comment by Luni-4** [comment]
I asked upstream https://github.com/jaseg/python-mpv/issues/144

Though, when I try to add the `self.mpv.wait_for_property('seekable')` instruction before the `mpv.seek` function in `bubblesub`, the program crashes brutally. Does it happen to you, @rr-, if you add that line?

**Comment by rr-** [comment]
It works fine with this patch:

```diff
diff --git a/bubblesub/ui/mpv.py b/bubblesub/ui/mpv.py
index 3814166..9e1d3f6 100644
--- a/bubblesub/ui/mpv.py
+++ b/bubblesub/ui/mpv.py
@@ -248,6 +248,7 @@ class MpvWidget(QtWidgets.QOpenGLWidget):
             self.mpv.end = ret
 
     def _on_request_seek(self, pts: int, precise: bool) -> None:
+        self.mpv.wait_for_property('seekable')
         self._set_end(None)  # mpv refuses to seek beyond --end
         self.mpv.seek(ms_to_str(pts), "absolute", "exact")
 
@@ -255,6 +256,7 @@ class MpvWidget(QtWidgets.QOpenGLWidget):
         self, start: T.Optional[int], end: T.Optional[int]
     ) -> None:
         if start is not None:
+            self.mpv.wait_for_property('seekable')
             self.mpv.seek(ms_to_str(start), "absolute")
         self._set_end(end)
         self.mpv.pause = False
```

**Comment by rr-** [comment]
You could play with
```
        if not self._api.playback.is_ready:
            return
```
that is used in a few places

**Comment by Luni-4** [comment]
> You could play with
> 
> ```
>         if not self._api.playback.is_ready:
>             return
> ```
> 
> that is used in a few places, I'd do that myself but I can't reproduce the issue on my local machine

I replaced this code with `self.mpv.wait_for_property('seekable')`, it doesn't work, but at least it doesn't crash anymore. What could be the problem in your opinion?

**Comment by rr-** [comment]
No idea :( I remember that even with pympv, you also experienced a crash
on program exit for bogus reasons that were not reproducible on my
machine…

**Comment by Luni-4** [comment]
Yeah, unfortunately. Perhaps some tests about those functions should be added such that our CI can intercept that

**Comment by rr-** [comment]
Actually one thing came to my mind, I had a crash in bubblesub-plugins not too long ago related to libass trying to render an event without any valid style. Maybe some of the problems are related to your libass?

**Comment by Luni-4** [comment]
Hmm, it seems strange to me, I used the `libass-dev` package to compile `mpv` and it works perfectly from command line and GUI. But I can try to build `libass` from `master` and then use that in `mpv`, thanks for the advice! :)

Actually I suspect the problem is related to `Qt` and how `bubblesub` handles threads, but I'm not sure about that.
